project:
  type: website
  output-dir: docs
  
website:
  title: "Jason Han"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: my_hometown.qmd     
        text: Why I Love Monterey 
      - href: resources_for_environmental_studies.qmd
        text: Resources for Environmental Studies     
      - href: resume.qmd
        text: Resume          
      - href: project.qmd
        text: Projects      
  page-footer:
    background: light
    left: Copyright 2025, Jason Han
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    css: styles.scss
    toc: true
    page-layout: full

editor: visual

