project:
  type: website
  output-dir: docs
website:
  title: "Jason Han"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume_CV.qmd
      - resources.qmd
      - project.qmd

format:
  html:
    theme: 
      light: brite
      dark: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

