project:
  type: website
  output-dir: docs
website:
  title: "Jason Han"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: my_hometown.qmd     
        text: Why I Love Monterey 
      - href: resources_for_environmental_studies.qmd
        text: Resources for Environmental Studies     
      - href: resume.qmd
        text: Resume          
      - href: project.qmd
        text: Projects        

format:
  html:
    theme: 
      light: brite
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

